Repository Financial-Times/o-header-services, pull requests merged in 2020-08, with the labels that each got.

#154 Add general usage to readme
  README.md
Labels: component, release:patch

#156 Correct dropdown border style within the drawer
  src/scss/_drawer.scss
  src/scss/_drop-down.scss
Labels: component, release:patch

#157 Use the new $default-branch macro instead of hardcoding the branch name
  .github/workflows/percy.yml
Labels: component

#163 Move to Github's native Dependabot
  .dependabot/config.yml
  .github/dependabot.yml
  .github/workflows/automerge.yml
Labels: component, dependencies

#166 remove the ci section from origami.json
  origami.json
Labels: component
